### ISSUE TITLE
Modify for wearable

### ISSUE THREAD

**Issue by SFrav** [tejado/Authorizer#1]
Would it be possible to port something like this to a wearable device?The aim would be to have something that is as small as possible that uses your USB feature. I've trawled through the code, but I'm far too inexperienced to know the limits of wearables (it seems very limited to me).

**Comment by tejado** [comment]
Maybe it is possible but the USB feature of Authorizer is dependent on a special kernel patch (https://github.com/pelya/android-keyboard-gadget) which has to be ported first to the respective wearable. Also I don't know much about wearables but I guess most smart watches have no micro USB or? Which sort of wearable do you have in mind?

**Comment by tejado** [comment]
If anyone is interessted (to support) in a smartwatch/wearable version of Authorizer, please contact me :)
Thanks!
