### ISSUE TITLE
add alternate soft keyboard to input password on the smartphone

### ISSUE THREAD

**Issue by lgasp** [tejado/Authorizer#12]
When trying to copy the password in the clipboard a warning popup suggests to use the Passwd alternate keyboard, instead of unsecure copy/paste.

Is it possible to implement this feature in Authorizer, too?

**Comment by tejado** [comment]
I never used this feature but I also didn't removed it from Authorizer. So you can activate the Authorizer keyboard in your Android input settings. I just tested it and it works :)

**Comment by lgasp** [comment]
That's good! I didn't think avout that! thank you for checking
