### ISSUE TITLE
Doesn't tell if user doesn't have root access  

### ISSUE THREAD

**Issue by EstebanZD** [tejado/Authorizer#13]
When using the app I noticed it didn't work, even on multiple devices, with different cables and everything, untill I used saw the changelog where it's the only place it says that the app uses root permissions in order to work.

Can you make it so that if root isn't granted, to tell the user? It would help many new users who think the app is broken or something.

**Comment by tejado** [comment]
Good point! I will check and fix it. Thanks for reporting it!

**Comment by swedneck** [comment]
It also needs to actively ask for root access, since magisk cannot give it without an app asking for it.

**Comment by tejado** [comment]
What is magisk?

**Comment by swedneck** [comment]
It's basically the de-facto root method nowadays.
https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445

**Comment by tejado** [comment]
Ah, I will have a look into that. Thanks! 
Are you aware of any open source app that implements root access over magisk?

**Comment by swedneck** [comment]
Syncthing (https://f-droid.org/packages/com.nutomic.syncthingandroid/) has an option to be run as superuser, under the experimental tab.

**Comment by jmichael2497** [comment]
seems like this needs special permissions to be manually added via adb or automatically via su (root).

should take a peek at open source apps with similar special permission needs like this logcat reader:

https://github.com/plusCubed/matlog/blob/master/app/src/main/java/com/pluscubed/logcat/helper/SuperUserHelper.java

**Comment by tejado** [comment]
@jmichael2497 feel free to contribute ;)

the sudo/root stuff can be found here: https://github.com/tejado/Authorizer/blob/master/authorizer/src/main/java/net/tjado/authorizer/OutputUsbKeyboardAsRoot.java

**Comment by jmichael2497** [comment]
i'm still at the stage of just helping by pointing more experienced folks to open source code examples, but eventually will work up to doing more stuff directly.

**Comment by tejado** [comment]
Added error message in case root access was rejected in commit https://github.com/tejado/Authorizer/commit/275e02fd28043b9e2d8ec7600d7c66f015b38a43.
Also it workes out of the box with the latest Magisk version. This means there are no modifications necessary to support Magisk.

Please notice, that this is not yet released in the stores.
