### ISSUE TITLE
Where is an OTP Button in keyboard?

### ISSUE THREAD

**Issue by kowith337** [tejado/Authorizer#14]
Since new update that I got from F-Droid is have support to add OTP in password database, but unfortunately, I cannot find the button to insert/autotype OTP in the app keyboard yet.

**Comment by tejado** [comment]
Currently, there is no dedicated button to type in the OTP. You can only generate OTP's manually or use the {OTP} Placeholder inside username/password (please see the README for all placeholders).

Would you like to have a seperate button to type in the OTP? If this makes sense from your perspective, I will think about it. 
Of course, feel free to create a patch & PR yourself :)

**Comment by tejado** [comment]
See: https://github.com/tejado/Authorizer/pull/19 thanks geco2!
