### ISSUE TITLE
Yubikey Neo support

### ISSUE THREAD

**Issue by Leviathan3DPrinting** [tejado/Authorizer#21]
I'd really like to see 2FA for logging into the password database, like their is on the normal passwdsafe application. If this was implemented idk if I'd ever use another password manager again. I'd use the normal passwdsafe app, but the USB otg function is something I absolutely love. Also is their any way to donate to this project if so please let me know.

**Comment by tejado** [comment]
Hi Leviathan220, so there is no "real" 2FA for things like local password databases as you can't prevent a replay attack. But anyway: Authorizer is build on passwdsafe and I didn't remove the Yubikey support so it should work :)

Currently there is no possibility to donate to this project but thanks! :)
