### ISSUE TITLE
Fingerprint support to access database. 

### ISSUE THREAD

**Issue by aTosser** [tejado/Authorizer#24]
It would be nice to have fingerprint support to access the database. KeePass dx has this functionality. Maybe you can get some inspiration from their codebase.

**Comment by tejado** [comment]
Great idea. As far as I know, also PasswdSafe already supports it. I will look into it as I already thought of implementing it but currently, I have no second smartphone with fingerprint sensor.

Any help here is highly welcome! :)

**Comment by aTosser** [comment]
I have a lineageOS fingerprint enabled tablet to test builds on but unfortunately Java and android are not my cup of tea.

**Comment by tejado** [comment]
So I checked it and Authorizer already supports accessing the database over fingerprint. As this part of the code comes from PasswdSafe, I wasn't sure.

You just need to check "Save password" (below the password input field) when opening a file.
Further instructions are available if you click at the ? in the menu.
