### ISSUE TITLE
Add a Stateless Password Generator

### ISSUE THREAD

**Issue by ghost** [tejado/Authorizer#25]
If you're unfamiliar with stateless passwords one popular implementation is lesspass. You can read up on how it works: https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4#.vbgschksh

Alright, so here's my vision for this use case:
Authorizer could live on an offline device and send these stateless passwords through keyboard emulation, increasing security as the master password is never entered on the target device. An attacker with a keylogger installed on your PC or a website database breach might be able to obtain passwords but never your master password or your OTPs. You can simply increment the counter to generate new password replacements as soon as you're aware of the breach. If your device is lost, stolen, or broken you'll never lose access to your accounts because you can simply generate the same passwords again in the future, and you don't have to worry about the thief having access to your passwords as nothing needs to be stored on disk.

You don't have to buy some fancy specialized security hardware. A small, cheap android device could do the job, hardening your security without sacrificing convenience. Authorizer is already quite close to making this a reality.

Security is hard, and I'm not an expert by any means but this seems like something to look into. Let me know what you think.

**Comment by tejado** [comment]
Hi,

thank you for your feature request.

I read about such deterministic passwords in the past and also good friends asked/suggested this feature in Authorizer. 

In my opinion, the idea is good but also flawed from security perspective. The reasons are described among other sources here:
- https://tonyarcieri.com/4-fatal-flaws-in-deterministic-password-managers (https://news.ycombinator.com/item?id=13016132)
- https://news.ycombinator.com/item?id=12889807

Also my plans for Authorizer will always require storing a "state", e.g. OTP or U2F.
So at least for me, I don't see any reason to implement this feature. 

But if you would like to integrate this feature in Authorizer yourself, I will help you with it :)

Tjado
