### ISSUE TITLE
Update F-Droid decription to let users know rooted device is required

### ISSUE THREAD

**Issue by sudomain** [tejado/Authorizer#28]
Similar to #13, it would be great if the fdroid description let users know that root is required for this app

**Comment by licaon-kter** [comment]
@sudomain this isn't in 0.4? https://github.com/tejado/Authorizer/commit/275e02fd28043b9e2d8ec7600d7c66f015b38a43

**Comment by tejado** [comment]
@sudomain 
It isn't required for the complete app - only for a small part of it. But yeah, it might make sense to add it.

**Comment by tejado** [comment]
As Bluetooth is now working (not yet in the latest release) without root, I close this.
