### ISSUE TITLE
lib version change

### ISSUE THREAD

**Issue by gspeiliu** [tejado/Authorizer#29]
Hi, while checking the source code of the previous version, I found that the version of one lib changed differently.
com.github.bmelnychuk:atv

It changed from 1.2.+ to 1.2.9
As we all know that + will match the latest version, why do we need to change 1.2.+ to 1.2.9?
Could you please tell me why? Thanks. :-)

**Comment by tejado** [comment]
Good question. As this was due to the migration to AndroidX, which is mostly done automatically by Android Studio, it could be an mistake by the IDE. But the fixed version does not matter... the atv project was not updated since years.

**Comment by tejado** [comment]
Is it okay to close this issue? :-) 
And out of curiosity: what is the reason for your questions?

**Comment by gspeiliu** [comment]
Yes, you can close this issue and sorry for the late response. I am trying to figure out the evolution of the versions of the libs used by Android project. :-)

**Comment by tejado** [comment]
Great, have fun with this :-)
