### ISSUE TITLE
Question about the Android attribute importantForAccessibility in passwdsafe_file screen

### ISSUE THREAD

**Issue by neves01** [tejado/Authorizer#35]
Hello guys,

I'm studying and testing the Authorizer app. Anyone know why the screen  **fragment_passwdsafe_open_file.xml** has in your input fields the attribute importantForAccessibility = **No**? Was it a security measure?

Thanks in advance.

**Comment by tejado** [comment]
Hi @neves01 
please see following pull request for more details: https://github.com/tejado/Authorizer/pull/10
