### ISSUE TITLE
Check if /dev/hidg0 exists before writing to it

### ISSUE THREAD

**Issue by CyberShadow** [tejado/Authorizer#36]
If it doesn't exist, then 

https://github.com/tejado/Authorizer/blob/a802bd497f61e53d0774a83e72878c1de9c93634/authorizer/src/main/java/net/tjado/authorizer/OutputUsbKeyboardAsRoot.java#L96

will just create a regular file called `/dev/hidg0`.

**Comment by tejado** [comment]
Good point - need to be fixed!

**Comment by tejado** [comment]
Fixed https://github.com/tejado/Authorizer/commit/6f1c252f0ad5f2f1db41602a1d4e92e40f1b198f
