### ISSUE TITLE
Authorizer was removed from Google Play Store

### ISSUE THREAD

**Issue by tejado** [tejado/Authorizer#37]
Authorizer was removed from Google Play Store due to some violation.
Need to get Authorizer compliant again.

**Comment by licaon-kter** [comment]
What's the status here exactly? 3 years since the last release.

FYI, I've re-enabled and updated Passwdsafe on F-Droid: https://gitlab.com/fdroid/fdroiddata/-/commit/eb5e51038630e04a1eb84c5909a42902f77f895f

**Comment by tejado** [comment]
Its back online since few weeks.
