### ISSUE TITLE
.csv import

### ISSUE THREAD

**Issue by ServOKio** [tejado/Authorizer#41]
Hello👋 In short, I would like to see support for importing passwords and logins from a `.csv` file. For example, in firefox, this file looks like this:
```
"url,"username","password","httpRealm","formActionOrigin","guid","timeCreated","timeLastUsed","timePasswordChanged"
https://site.com,"helloworld@yahoo.com","password",,"https://site.com","87f23f23f","1649905569125","1649906459007","1649905569125"
```

url | username | password | httpRealm | formActionOrigin | guid | timeCreated | timeLastUsed | timePasswordChanged
--- | --- | --- | --- |--- |--- |--- |--- |---
https://site.com | helloworld@yahoo.com | password |   | https://site.com | 87f23f23f | 1649905569125 | 1649906459007 | 1649905569125

**Comment by tejado** [comment]
You can try to use the desktop pwsafe application to import your entries - it is supporting CSV:
https://pwsafe.org/
https://pwsafe.org/help/pwsafeEN/html/import.html

The database format should be compatible. Please test this carefully. If this is working or not, please tell us your experience.
