### ISSUE TITLE
Wrong keyboard events from Authorizer.

### ISSUE THREAD

**Issue by vi** [tejado/Authorizer#42]
I ask Authoritzer to type `ttt` on USB keyboard gadget, and get these events instead:

<details><summary>evdev-dump events</summary>

```
/dev/input/event21 1659630959.601249 EV_MSC MSC_SCAN 0x000700E0
/dev/input/event21 1659630959.601249 EV_KEY KEY_LEFTCTRL 0x00000001
/dev/input/event21 1659630959.601249 EV_MSC MSC_SCAN 0x000700E1
/dev/input/event21 1659630959.601249 EV_KEY KEY_LEFTSHIFT 0x00000001
/dev/input/event21 1659630959.601249 EV_MSC MSC_SCAN 0x000700E2
/dev/input/event21 1659630959.601249 EV_KEY KEY_LEFTALT 0x00000001
/dev/input/event21 1659630959.601249 EV_MSC MSC_SCAN 0x000700E4
/dev/input/event21 1659630959.601249 EV_KEY KEY_RIGHTCTRL 0x00000001
/dev/input/event21 1659630959.601249 EV_SYN SYN_REPORT 0x00000001
/dev/input/event21 1659630959.602216 EV_MSC MSC_SCAN 0x000700E0
/dev/input/event21 1659630959.602216 EV_KEY KEY_LEFTCTRL 0x00000000
/dev/input/event21 1659630959.602216 EV_MSC MSC_SCAN 0x000700E1
/dev/input/event21 1659630959.602216 EV_KEY KEY_LEFTSHIFT 0x00000000
/dev/input/event21 1659630959.602216 EV_MSC MSC_SCAN 0x000700E2
/dev/input/event21 1659630959.602216 EV_KEY KEY_LEFTALT 0x00000000
/dev/input/event21 1659630959.602216 EV_MSC MSC_SCAN 0x000700E4
/dev/input/event21 1659630959.602216 EV_KEY KEY_RIGHTCTRL 0x00000000
/dev/input/event21 1659630959.602216 EV_SYN SYN_REPORT 0x00000001
/dev/input/event21 1659630959.617249 EV_MSC MSC_SCAN 0x000700E0
/dev/input/event21 1659630959.617249 EV_KEY KEY_LEFTCTRL 0x00000001
/dev/input/event21 1659630959.617249 EV_MSC MSC_SCAN 0x000700E1
/dev/input/event21 1659630959.617249 EV_KEY KEY_LEFTSHIFT 0x00000001
/dev/input/event21 1659630959.617249 EV_MSC MSC_SCAN 0x000700E2
/dev/input/event21 1659630959.617249 EV_KEY KEY_LEFTALT 0x00000001
/dev/input/event21 1659630959.617249 EV_MSC MSC_SCAN 0x000700E4
/dev/input/event21 1659630959.617249 EV_KEY KEY_RIGHTCTRL 0x00000001
/dev/input/event21 1659630959.617249 EV_SYN SYN_REPORT 0x00000001
/dev/input/event21 1659630959.618250 EV_MSC MSC_SCAN 0x000700E0
/dev/input/event21 1659630959.618250 EV_KEY KEY_LEFTCTRL 0x00000000
/dev/input/event21 1659630959.618250 EV_MSC MSC_SCAN 0x000700E1
/dev/input/event21 1659630959.618250 EV_KEY KEY_LEFTSHIFT 0x00000000
/dev/input/event21 1659630959.618250 EV_MSC MSC_SCAN 0x000700E2
/dev/input/event21 1659630959.618250 EV_KEY KEY_LEFTALT 0x00000000
/dev/input/event21 1659630959.618250 EV_MSC MSC_SCAN 0x000700E4
/dev/input/event21 1659630959.618250 EV_KEY KEY_RIGHTCTRL 0x00000000
/dev/input/event21 1659630959.618250 EV_SYN SYN_REPORT 0x00000001
/dev/input/event21 1659630959.633248 EV_MSC MSC_SCAN 0x000700E0
/dev/input/event21 1659630959.633248 EV_KEY KEY_LEFTCTRL 0x00000001
/dev/input/event21 1659630959.633248 EV_MSC MSC_SCAN 0x000700E1
/dev/input/event21 1659630959.633248 EV_KEY KEY_LEFTSHIFT 0x00000001
/dev/input/event21 1659630959.633248 EV_MSC MSC_SCAN 0x000700E2
/dev/input/event21 1659630959.633248 EV_KEY KEY_LEFTALT 0x00000001
/dev/input/event21 1659630959.633248 EV_MSC MSC_SCAN 0x000700E4
/dev/input/event21 1659630959.633248 EV_KEY KEY_RIGHTCTRL 0x00000001
/dev/input/event21 1659630959.633248 EV_SYN SYN_REPORT 0x00000001
/dev/input/event21 1659630959.634251 EV_MSC MSC_SCAN 0x000700E0
/dev/input/event21 1659630959.634251 EV_KEY KEY_LEFTCTRL 0x00000000
/dev/input/event21 1659630959.634251 EV_MSC MSC_SCAN 0x000700E1
/dev/input/event21 1659630959.634251 EV_KEY KEY_LEFTSHIFT 0x00000000
/dev/input/event21 1659630959.634251 EV_MSC MSC_SCAN 0x000700E2
/dev/input/event21 1659630959.634251 EV_KEY KEY_LEFTALT 0x00000000
/dev/input/event21 1659630959.634251 EV_MSC MSC_SCAN 0x000700E4
/dev/input/event21 1659630959.634251 EV_KEY KEY_RIGHTCTRL 0x00000000
/dev/input/event21 1659630959.634251 EV_SYN SYN_REPORT 0x00000001
```

</details>

[`hid_gadget_test`](https://github.com/aagallag/hid_gadget_test), for example, does type keys correctly, so I assume the problem is with Authorizer itself.

The same version of Authorizer work before on the same device on Android 11, but with Android 12 it seems to be failing.

**Comment by vi** [comment]
I see the following command line being executed by Authorizer:

```
printf '\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' > /dev/hidg0
```

Executing it manually also emits the same wrong keyboard events as from the Authorizer.

**Comment by vi** [comment]
Looks like `printf` writes one byte at a time, which gadget drivers does not like.

Workaround:

```
printf '\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x17\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' \
  | dd of=/dev/hidg0 bs=8
```

**Comment by tejado** [comment]
Hi @vi 
Thanks a lot for analysing this issue and providing a solution. There was at least one previous issue by users mentioning a similar problem. 
I had never any issue with it. Do you know if this issue is part of every printf implementation? If not, I wonder why I did not hit it so far. 
Can you provide information about your environment at Android 12, e.g. your shell and version of it? Thanks!

**Comment by vi** [comment]
What do you mean by "shell version"? `/system/bin/sh` does not seem to provide version information.

```
$ /system/bin/printf --version
toybox 0.8.4-android
```

The system is `crosshatch-sp1a.210812.016.c2` with Magisk `25.1 (25100)`.

**Comment by tejado** [comment]
> toybox

Great thanks. And on your Android 11, was this also toybox or busybox and which version?

**Comment by vi** [comment]
On another (unrooted) device with Android 11 I see:

```
$ /system/bin/printf --version
toybox 0.8.3-android
```

I do not see any relevant changes in `printf` subcommand between toybox 0.8.3 and 0.8.4.

Note that `printf` can also be a build-in command in shell.

Also note that different Linux kernels may react differently to short writes to character devices.

**Comment by Alexander-Shukaev** [comment]
Happy to test as per #38.

**Comment by vi** [comment]
@Alexander-Shukaev , Does it work better with #43?

Does `echo g g | hid_gadget_test /dev/hidg0 keyboard` work reliably for you?

**Comment by Alexander-Shukaev** [comment]
I don't know how to test this without release really.

**Comment by tejado** [comment]
I will provide tomorrow a test apk, so we can verify if this is working on several devices.

**Comment by vi** [comment]
Here is the apk I use for myself.

[authorizer-debug.zip](https://github.com/tejado/Authorizer/files/9276664/authorizer-debug.zip)

**Comment by Alexander-Shukaev** [comment]
How to install it on Android?

**Comment by vi** [comment]
Rename it to `authorizer-debug.apk`, then `adb install authorizer-debug.apk` (if USB debugging is in use).
Or copy it to the device, then open it with a file manager (you may need to accept that file manager as application installation source).

Note that installing apks in this way (including ones downloaded from Github) is a security risk. If you want both root access and security, you should be prepared to configure Android development environment to build things from source code (and review that source at least superficially).

**Comment by Alexander-Shukaev** [comment]
Installing directly on the device, it says "App not installed", so the installation basically fails...  Any ideas?

**Comment by tejado** [comment]
> Installing directly on the device, it says "App not installed", so the installation basically fails... Any ideas?

Do you have it already installed on your device? Because then the signature of vi's apk will not match the one of the already installed app. You have to deinstall it before installing the new one.
And do this test only on a device which does not contain anything sensitive.

Thanks @vi for providing the apk. I will need some days to test it to prepare my dev devices, which I used for something else.

**Comment by Alexander-Shukaev** [comment]
@vi and @tejado, thanks for the tips and working on this.  I can confirm through several test cases, which failed before, that the debug version that @vi provided now types passwords as expected!  Incredible 🥂 💯

**Comment by tejado** [comment]
Great, thanks for the feedback @Alexander-Shukaev. It could be, that this issue hit me the first time today as well. So my priority on this increased and will check the fix as well asap.

**Comment by vi** [comment]
Shall I expect an F-Droid build with my patch (or some another fix) someday?

**Comment by tejado** [comment]
> Shall I expect an F-Droid build with my patch (or some another fix) someday?

Hi vi, 
unfortunately, my issue had nothing to do with your fix. I need still some time to prepare my environment, as I preparing the builds on a new (Pixel) device with a different custom rom.
I hope I'm finishing this in the next days. If everything works fine, I will merge it and trigger an f-droid build.

**Comment by Alexander-Shukaev** [comment]
Hi, it's been a while now since I tested the patch.  @tejado, do you have some rough ETA for F-Droid please?  Thanks!

**Comment by vi** [comment]
Maybe it also worth to change it to [avoid creating regular file `/dev/hidg0` when character device does not exist][1] along the way?

[1]:https://github.com/tejado/Authorizer/issues/36

**Comment by tejado** [comment]
> Hi, it's been a while now since I tested the patch. @tejado, do you have some rough ETA for F-Droid please? Thanks!

Give me a few more days. Latest end of next week. Having a summer break right now but I try my best to merge and schedule f-droid build asap.

> Maybe it also worth to change it to [avoid creating regular file `/dev/hidg0` when character device does not exist](https://github.com/tejado/Authorizer/issues/36) along the way?

Sure - there are even more things to fix/implement. At first I need to update my own devices as mentioned above, as these are currently based on the Kernel patch which has not such issues. When I'm done with that, I will implement more fixes, e.g. adding gadgets at boot time, ...

**Comment by tejado** [comment]
Change was merged and additionally bugs were resolved to create a new release with minimum efforts. F-Droid build process should pick it up in their next update phase (few days).

@vi 
I will now start the work on v0.5.0 which will be using latest SDKs, e.g. to get it ready for Play Store. This will then also include better compatibility with android-usb-gadget, e.g. fixing #36.

**Comment by vi** [comment]
Offtopic here, but does it make sense to bundle some of [USB Gadget Tool](https://github.com/tejado/android-usb-gadget) functions (i.e. adding keyboard gadget if it does not exist) into Authorizer itself?

**Comment by tejado** [comment]
> Offtopic here, but does it make sense to bundle some of [USB Gadget Tool](https://github.com/tejado/android-usb-gadget) functions (i.e. adding keyboard gadget if it does not exist) into Authorizer itself?

Maybe at a later point. Currently, the USB Gadget Tool is very unstable on some devices. E.g. it is required to add a new gadget instead of just adding the HID function to the existing gadget. Doing this automatically, can cause other USB functions to fail so that a reboot will be required (e.g. to get adb working again). But I will have to check how the overall experience with Authorizer and USB Gadget Tool can look like as soon as I use it together on a daily basis.

**Comment by tejado** [comment]
The new version is now available in the F-Droid store: https://f-droid.org/en/packages/net.tjado.passwdsafe/
