### ISSUE TITLE
Typing over USB doesn't work (Mac, Xiaomi Mi6)

### ISSUE THREAD

**Issue by nchursin** [tejado/Authorizer#47]
Hi @tejado!

Awesome app I'd really like to use, but I have an issue. When I try to "type" the password, nothing happens.

I have your USB Gadget Tool installed and I added hid.keyboard function to the default gadget (g1). I also tried to use a separate gadget, but no luck.

Setup:
1. Phone: Xiaomi Mi6
2. Android 9, MIUI 11
3. Rooted with Magisk, if that helps.
4. Mac, MacOS Monterey
5. I tried a simple USB-C->USB-C cable and a USB-C->USB one, but looks like my Mac sees the phone as a keyboard. At least it shows a popup saying "Configure your keyboard"
6. I also have an external keyboard

It also keep spamming with "Root permission granted" when I tap the "type" button

Attaching the logs I got form the debug version
[type.log](https://github.com/tejado/Authorizer/files/10030075/type.log)

P.S. Also my additional gadget in the USB Gadget Tool goes missing after I reboot the phone.

**Comment by tejado** [comment]
Hi @nchursin 
Thank you. I never tested USB Gadget Tool with MacOS. Just recently, I added a fix for using it under iOS. 
I will have a look on it.

Regarding the missing gadget after reboot: the gadget configuration is temporary. I added a boot configuration to add and activate gadgets during boot time. But I did not provide a release yet, so you have to build USB Gadget Tool yourself if you dont want to wait for me :)

**Comment by tejado** [comment]
I tested it on a MacBook Air with MacOS Monterey and it did work. I had to configure the keyboard at first over the dialog which pops up when I connected it.
Can you please show me your USB Gadget Tool log? 

Can you also please try to add a completely new gadget, not adding functions to the existing one (this might not work due to other system functions like adb) and then providing me the log of USB Gadget Tool? Thanks.

**Comment by nchursin** [comment]
hmm, which app have you used to configure the keyboard? It asks me to press keys next to shifts. I tried to trick it using my regular keyboard, but didn't work.

I'll send you the USB GT logs a bit later today.

**Comment by tejado** [comment]
> hmm, which app have you used to configure the keyboard? It asks me to press keys next to shifts. I tried to trick it using my regular keyboard, but didn't work.
> 
> I'll send you the USB GT logs a bit later today.

You can click next there and then you have the option to select a specific keyboard. When I selected the European one it worked.

**Comment by nchursin** [comment]
Lol, mate, sorry for bothering. I have no idea what has happened, but today I plugged in the device and it just worked! :)

Thank you for your support and the app
