### ISSUE TITLE
Add compatibility with keepass ?

### ISSUE THREAD

**Issue by djmemo** [tejado/Authorizer#5]
It is possible to add compatibility to open the files keepass?

**Comment by tejado** [comment]
Hi,

Authorizer is compatible to Password Safe (https://pwsafe.org/) and PasswdSafe for Android (https://sourceforge.net/p/passwdsafe/wiki/Home/).
According to the keepass page, you can import passwords from Password Safe files but I didn't test it. If you have any results, it would be great if you can post them here.

Regards
Tjado
