### ISSUE TITLE
0.5.0 can't open in-file folders

### ISSUE THREAD

**Issue by licaon-kter** [tejado/Authorizer#62]
F-Droid version, Android 11 

(Not a storage issue, I can open the file, just that the tree folders can't be opened)

**Comment by tejado** [comment]
Which view are you using? Default tree view or the classic view?
Wha happens if you want to open a folder?

**Comment by licaon-kter** [comment]
Classic View, while Tree appears to work

Touching a folder does nothing

**Comment by tejado** [comment]
Thank you - I'm usually using the tree view so I forgot testing the classic one. I will have a look into it. 

Good to know that people still using the classic one :) As there is no telemetry in the app, its hard to know what features users are using.

**Comment by tejado** [comment]
Got it fixed. Will prepare a new release in the next days.
