### ISSUE TITLE
Sending via USB not working

### ISSUE THREAD

**Issue by mioux** [tejado/Authorizer#8]
On my nexus 5, I installed the linked kernel, rooted via SuperSU, I can't send text via USB.

It has been downgraded to 5.0 from 6.0, USB Keyboard app is installed, and when I use Authorizer as keyboard for USB Keyboard, I can enter the logins and passwords.

**Comment by tejado** [comment]
Hi,

thanks for posting your issue. Can you provide me a logcat output of Authorizer when the text should be send to the device? Also you can send it per mail.
If possible, please use the [v0.2.4 debug apk](https://github.com/tejado/Authorizer/releases/tag/v0.2.4-beta) for this, which will have much more details in the logcat. But then ensure, that you create a test entry with a test password as the logcat would contain the details what should be send via USB (so the password...). 

Thanks! 
Tjado

**Comment by absturztaube** [comment]
just a side note. i had something similar. in my case, i had no xxd on my device. i had do build it for myself and after the deployment, it worked like a charm.

**Comment by mioux** [comment]
Hi !

Here it is, with 0.24-debug ;)

I have used a "test.psafe3" file, with "test" entry which is set up with "testlogin" and "testpw"

[2017-08-21-09-32-31.txt](https://github.com/tejado/Authorizer/files/1238147/2017-08-21-09-32-31.txt)

EDIT I don't have filtered by package (I don't know if it is possible indeed 😸 )

**Comment by absturztaube** [comment]
Is xxd installed? open an adb shell and type xxd (maybe as root)

**Comment by absturztaube** [comment]
btw. i have a build of xxd here: https://cloud.geek.ch/index.php/s/FIsgGLwohQJEsUI

**Comment by mioux** [comment]
My phone has decided to reboot every 10s...it will need a physical fix before I can test

**Comment by mioux** [comment]
Ok... The phone won't boot again....

Sorry, I won't be able to repair it, the power button is dead, I don't have the tools to repair it. If it had been the plastic part, I would have removed it, and powered the phone with a mini stick, but it's the internal button which is broken.

If i find a compatible phone, I'll reinstall the app...

(Maybe you know a compatible kernel for a wileyfox swift running LineageOS 14.1)

_Sent from my Wileyfox Swift using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mioux** [comment]
I have read that smashing the power button can repair it... And it worked :D

I have install busybox from fdroid, which provides `xxd` it does not work.

_Sent from my Wileyfox Swift using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tejado** [comment]
I can recommend to build the kernel yourself. It is not so difficult. The lineageos wiki has a good description of the build process, also for [wileyfox swift](https://wiki.lineageos.org/devices/crackling/build).

So I don't see any issues in your log. If xxd would not be available it should be visible in there... :/
Do you have SELinux activated? If you have a terminal, you can check it over the command "getenforce". Otherwise it should be somewhere visible in the settings details next to kernel infos and so on (as SELinux-Status).

**Comment by mioux** [comment]
# getenforce
    Enforcing
    # setenforce 0
    # getenforce
    Permissive

No changes 😭

**Comment by absturztaube** [comment]
i got now the same problem when using xxd from busybox from fdroid. it seems that the xxd variant in busybox does not understand the -r switch. the xxd command then shows the help output

**Comment by tejado** [comment]
Okay thanks. I will check the replacement of xxd.

**Comment by mioux** [comment]
I just have checked... It does not work with xxd provided with xxd provided with [this busybox](https://f-droid.org/packages/ru.meefik.busybox/).

It works with the xxd provided by @absturztaube 

FYI : this is the xxd --help from busybox

    root@hammerhead:/system/bin # /system/xbin/xxd --help                          
    BusyBox v1.27.1-meefik (2017-08-11 21:12:02 BST) multi-call binary.
    
    Usage: xxd [OPTIONS] [FILE]
    
    Hex dump FILE (or stdin)
    
    	-g N		Bytes per group
    	-c N		Bytes per line
    	-p		Show only hex bytes, assumes -c30
    	-l LENGTH	Show only first LENGTH bytes
    	-s OFFSET	Skip OFFSET bytes

**Comment by absturztaube** [comment]
btw: i builded xxd from this source: https://github.com/andrew-d/static-binaries

**Comment by mioux** [comment]
Using busybox from Magisk, it works (xxd -r is working :smile:)

**Comment by absturztaube** [comment]
huh?
i installed magisk and its busybox module. but i can't use the reverse switch on xxd. @mioux can you provide a link to the busybox please?

**Comment by mioux** [comment]
It's exactly what I have done :)

I have installed version 13.6 beta of Magisk, and used the manager to download and install busybox. 

_Sent from my Wileyfox Swift using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by absturztaube** [comment]
i just reflashed my phone and can confirm, that the hexdump tool from magisk busybox works (as of today magisk version 14.0)

**Comment by absturztaube** [comment]
@tejado why is this issue still open? You can close this one, i think.

**Comment by tejado** [comment]
I have not closed this as I would like to make some changes to the hex encoding.

**Comment by tejado** [comment]
I replaced xxd with printf in commit https://github.com/tejado/Authorizer/commit/0439350d9e5e38fd245b470fb517760848f2a136. This should have a better compability.
