### ISSUE TITLE
Implement bluetooth keyboard functionality similar to USB keyboard

### ISSUE THREAD

**Issue by Nothing4You** [tejado/Authorizer#9]
Hey there,
I don't know whether this is even possible at all nor securely, this would definitely require some investigation, however, if this is doable without security concerns this could be a great feature.

It would need android to be able to behave as a bt keyboard and it would have to be looked at possible security issues like traffic sniffing (reading keys or at least being able to replay them).

**Comment by tejado** [comment]
Hi,
yes, basically this is already on the roadmap. Sadly, it is not so easy as Android is not anymore using BlueZ as the bluetooth stack but Bluedroid. So I looked at some projects like https://github.com/kshoji/BLE-HID-Peripheral-for-Android but I couldn't get them to work. 

So my current task in regard to Authorizer is to integrate OTP (merging FreeOTP into Authorizer). After this, maybe I will then look again further into the Bluetooth topic. 

Of course, any help to Authorizer is highly appreciated :)

**Comment by tejado** [comment]
For your information:
Bluetooth is possible and will be implemented in one of the next releases. But this could take a while. If someone is interessted to help to integrate this, I can provide further technical details for it.

**Comment by contrun** [comment]
@tejado care to clarify how to do it? O am intrigued.

**Comment by tejado** [comment]
Just to know how it is implemented or do you want to help to integrate this?

Feel free to join our mattermost for better communication :) 
https://github.com/tejado/Authorizer/blob/master/README.md#contributions--community

**Comment by jmichael2497** [comment]
searching for example Bluetooth USB adapter dongle with HID proxy mode support, i came across a few relevant items of interest, maybe you've already seen them?

https://code.google.com/archive/p/androhid (abandoned 2010) on using root to add BT profile to mobile directly, no extra hardware adapter needed.

https://github.com/PhilippC/keepass2android has support for hardware adapter based...

https://github.com/inputstick via plugins and BT or BTLE to USB HID proxy adapter.

see news updates at http://blog.inputstick.com looks like they've updated ios related code so android next.

hope that helps open source powers combine.

**Comment by tejado** [comment]
I implemented the Bluetooth functionality now over the BluetoothHid API which is available since Android Pie (28). Please see commit https://github.com/tejado/Authorizer/commit/3db0a873bfc010b7fcbdbfd149a3a0b7580f0c83 

Please notice, that this is not yet released in the stores.

**Comment by zhubinsheng** [comment]
> 我现在通过 BluetoothHid API 实现了蓝牙功能，该 API 从 Android Pie (28) 开始可用。请参阅提交[3db0a87](https://github.com/tejado/Authorizer/commit/3db0a873bfc010b7fcbdbfd149a3a0b7580f0c83)
> 
> 请注意，这尚未在商店中发布。
if use https://github.com/kshoji/BLE-HID-Peripheral-for-Android ,work ok ?
